### ISSUE TITLE
Running userinfo without arguments causes an error.

### ISSUE THREAD

**Issue by IDeletedSystem64** [IDeletedSystem64/anitrox#41]
When running userinfo without mentioning an user, it produces an error like
```
TypeError: Cannot read property 'presence' of undefined
at Object.execute (/home/container/commands/userinfo.js:13:20)
at Client.<anonymous> (/home/container/start.js:63:32)
at Client.emit (events.js:376:20)
at MessageCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
at Object.module.exports [as MESSAGE_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:132:16)
at WebSocket.emit (events.js:376:20)```

What should happen is it runs the command on the user who ran it, then doesn't have a playing status

**Comment by IDeletedSystem64** [comment]
Closed in 1.0
